# Generated by Django 3.1.6 on 2021-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
